# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import LOCAL_SK_pb2 as LOCAL__SK__pb2


class WSStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.clientStream = channel.unary_unary(
        '/WS/clientStream',
        request_serializer=LOCAL__SK__pb2.toClient.SerializeToString,
        response_deserializer=LOCAL__SK__pb2.fromClient.FromString,
        )


class WSServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def clientStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WSServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'clientStream': grpc.unary_unary_rpc_method_handler(
          servicer.clientStream,
          request_deserializer=LOCAL__SK__pb2.toClient.FromString,
          response_serializer=LOCAL__SK__pb2.fromClient.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'WS', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
