# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LOCAL_SK.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='LOCAL_SK.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eLOCAL_SK.proto\"\x1e\n\x08toClient\x12\x12\n\non_mission\x18\x01 \x01(\x08\"\x1b\n\nfromClient\x12\r\n\x05image\x18\x01 \x01(\x0c\x32.\n\x02WS\x12(\n\x0c\x63lientStream\x12\t.toClient\x1a\x0b.fromClient\"\x00\x62\x06proto3')
)




_TOCLIENT = _descriptor.Descriptor(
  name='toClient',
  full_name='toClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='on_mission', full_name='toClient.on_mission', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=48,
)


_FROMCLIENT = _descriptor.Descriptor(
  name='fromClient',
  full_name='fromClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='fromClient.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['toClient'] = _TOCLIENT
DESCRIPTOR.message_types_by_name['fromClient'] = _FROMCLIENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

toClient = _reflection.GeneratedProtocolMessageType('toClient', (_message.Message,), dict(
  DESCRIPTOR = _TOCLIENT,
  __module__ = 'LOCAL_SK_pb2'
  # @@protoc_insertion_point(class_scope:toClient)
  ))
_sym_db.RegisterMessage(toClient)

fromClient = _reflection.GeneratedProtocolMessageType('fromClient', (_message.Message,), dict(
  DESCRIPTOR = _FROMCLIENT,
  __module__ = 'LOCAL_SK_pb2'
  # @@protoc_insertion_point(class_scope:fromClient)
  ))
_sym_db.RegisterMessage(fromClient)



_WS = _descriptor.ServiceDescriptor(
  name='WS',
  full_name='WS',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=79,
  serialized_end=125,
  methods=[
  _descriptor.MethodDescriptor(
    name='clientStream',
    full_name='WS.clientStream',
    index=0,
    containing_service=None,
    input_type=_TOCLIENT,
    output_type=_FROMCLIENT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WS)

DESCRIPTOR.services_by_name['WS'] = _WS

# @@protoc_insertion_point(module_scope)
