# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SK.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SK.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x08SK.proto\"/\n\nfromClient\x12\x12\n\non_mission\x18\x01 \x01(\x08\x12\r\n\x05image\x18\x02 \x01(\x0c\"L\n\x08toClient\x12\x10\n\x08\x64istance\x18\x01 \x01(\x05\x12\n\n\x02tx\x18\x02 \x01(\x05\x12\n\n\x02ty\x18\x03 \x01(\x05\x12\n\n\x02\x62x\x18\x04 \x01(\x05\x12\n\n\x02\x62y\x18\x05 \x01(\x05\x32.\n\x02WS\x12(\n\x0c\x63lientStream\x12\x0b.fromClient\x1a\t.toClient\"\x00\x62\x06proto3')
)




_FROMCLIENT = _descriptor.Descriptor(
  name='fromClient',
  full_name='fromClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='on_mission', full_name='fromClient.on_mission', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='fromClient.image', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=59,
)


_TOCLIENT = _descriptor.Descriptor(
  name='toClient',
  full_name='toClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='distance', full_name='toClient.distance', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tx', full_name='toClient.tx', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ty', full_name='toClient.ty', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bx', full_name='toClient.bx', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='by', full_name='toClient.by', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=137,
)

DESCRIPTOR.message_types_by_name['fromClient'] = _FROMCLIENT
DESCRIPTOR.message_types_by_name['toClient'] = _TOCLIENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

fromClient = _reflection.GeneratedProtocolMessageType('fromClient', (_message.Message,), dict(
  DESCRIPTOR = _FROMCLIENT,
  __module__ = 'SK_pb2'
  # @@protoc_insertion_point(class_scope:fromClient)
  ))
_sym_db.RegisterMessage(fromClient)

toClient = _reflection.GeneratedProtocolMessageType('toClient', (_message.Message,), dict(
  DESCRIPTOR = _TOCLIENT,
  __module__ = 'SK_pb2'
  # @@protoc_insertion_point(class_scope:toClient)
  ))
_sym_db.RegisterMessage(toClient)



_WS = _descriptor.ServiceDescriptor(
  name='WS',
  full_name='WS',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=139,
  serialized_end=185,
  methods=[
  _descriptor.MethodDescriptor(
    name='clientStream',
    full_name='WS.clientStream',
    index=0,
    containing_service=None,
    input_type=_FROMCLIENT,
    output_type=_TOCLIENT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WS)

DESCRIPTOR.services_by_name['WS'] = _WS

# @@protoc_insertion_point(module_scope)
